version: '3.2'

services:
  localstack:
    image: localstack/localstack-full
    ports:
      #dynamodb
      - "4569:4569"
      #dynamodb shell
      - "4564:4564"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=local
      - LAMBA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  app:
    build: .
    volumes:
      - .:/src
    restart: on-failure
    #command: npm test
    ports:
      - 3000:3000
    links:
      - localstack
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOST=localstack
      - DYNAMODB_PORT=4569

